version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5435:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=phoenix_crud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=phoenix_crud